---
services:
  node-red:
    image: nodered/node-red
    container_name: node-red
    ports:
      - "6335:1880"
    network_mode: bridge
    volumes:
      - "/opt/node-red:/data"
    environment:
      - TZ=Europe/Zagreb
    restart: unless-stopped
