---
services:
  node-red:
    image: nodered/node-red
    container_name: node-red
    command: "-R 1000:1000 /opt/node-red"
    ports:
      - "6335:1880"
    network_mode: bridge
    volumes:
      - node-red-data:/data
    environment:
      - TZ=Europe/Zagreb
    restart: unless-stopped

volumes:
  node-red-data:
