---
volumes:
  data:
    name: node-red_data

services:
  node-red:
    image: nodered/node-red
    container_name: node-red
    command: "-R 1000:1000 /opt/node-red"
    ports:
      - "1880:1880"
    dns:
      - 1.1.1.1
      - 8.8.8.8
    volumes:
      - data:/data
    environment:
      - TZ=Europe/Zagreb
    restart: unless-stopped
