services:
  caddy:
    image: ghcr.io/caddybuilds/caddy-cloudflare:latest
    container_name: caddy
    command: ["caddy", "run", "--config", "/etc/caddy/config.json"]
    env_file:
      - .env
    environment:
      - CLOUDFLARE_EMAIL=${CF_EMAIL}
      - CLOUDFLARE_API_TOKEN=${CF_API_TOKEN}
      - ACME_AGREE=true
    ports:
      - 2019:2019 # remove if you do not want admin API
      - 80:80
      - 443:443
    volumes:
      - /opt/caddy/config.json:/etc/caddy/config.json:ro
      - /opt/caddy/config:/config
      - /opt/caddy/data:/data
    networks:
      - proxy
    restart: unless-stopped

# create this first before running the docker-compose - docker network create caddy
networks:
  proxy:
    external: true
