version: 4
homeassistant:
  enabled: true
  discovery_topic: client/[id]/ha
  status_topic: client/[id]/ha/status
  legacy_entity_attributes: false
  legacy_triggers: false
mqtt:
  base_topic: client/[id]/z2m
  server: mqtt://mosquitto:1883
  discovery: true
  discovery_prefix: client/[id]/ha
serial:
  port: /dev/ttyUSB0
  adapter: ember
  baudrate: 115200
frontend:
  enabled: true
  port: 8080
  host: 0.0.0.0
advanced:
  log_level: info
  retain: true
  watchdog:
    enabled: true
  channel: 11
  network_key: GENERATE
