---
services:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:2.7.2
    container_name: zigbee2mqtt
    ports:
      - 8080:8080
    networks:
      - proxy
    environment:
      - TZ=Europe/Zagreb
    volumes:
      - ./data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      # Make sure this matched your adapter location
      - /dev/serial/by-id/usb-SONOFF_SONOFF_Dongle_Lite_MG21_c0fa0ce36e8bef11a6a822ccef8776e9-if00-port0:/dev/ttyUSB0
    restart: unless-stopped

networks:
  proxy:
    external: true
