---
services:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:latest
    container_name: zigbee2mqtt
    ports:
      - 8080:8080
    environment:
      - TZ=Europe/Zagreb
    volumes:
      - ./data:/app/data
      - ./certs:/app/certs # Mount folder with ca.crt if using secure MQTT
      - /run/udev:/run/udev:ro
    devices:
      # Make sure this matched your adapter location
      - /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0018ED3DDF-if00:/dev/ttyACM0
    restart: unless-stopped
