---
services:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:2.7.2
    container_name: z2m
    ports:
      - 8080:8080
    networks:
      - proxy
    environment:
      - TZ=Europe/Zagreb
    volumes:
      - ./data:/app/data
      - /run/udev:/run/udev:ro
    #devices:
    # Make sure this matched your adapter location if using a USB dongle
    #- /dev/serial/by-id/usb-SONOFF_SONOFF_Dongle_Lite_MG21_fad4b11988a0ef11b5baa1a361ce3355-if00-port0:/dev/ttyUSB0
    restart: unless-stopped

networks:
  proxy:
    external: true
