services:
  mosquitto:
    image: eclipse-mosquitto:2.1.0-alpine
    container_name: mosquitto
    ports:
      - "21883:1883" # MQTT
      - "8883:8883" # MQTTS (secure)
      - "9001:9001" # WebSockets
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
      - /etc/letsencrypt/archive/mqtt.local:/mosquitto/certs
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true
