---
services:
  homeassistant:
    image: homeassistant/home-assistant:stable
    container_name: homeassistant
    ports:
      - 8123:8123
    dns:
      - 1.1.1.1
      - 8.8.8.8
    healthcheck:
      test: "curl --connect-timeout 10 --silent -f http://127.0.0.1:8123/ || exit 1"
      interval: 30s
      timeout: 10s
      retries: 6
    volumes:
      - /opt/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Zagreb
    restart: always
